### ISSUE TITLE
ERROR: InvocationError for command

### ISSUE THREAD

**Issue by Tronde** [linux-system-roles/tox-lsr#72]
Hi,  
I've some trouble getting started doing integration testing with `tox-lsr` and `qemu`.

Information about my environment:

~~~
OS: Fedora 35
$ python3 --version
Python 3.10.3

$ ansible --version
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/home/tronde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tronde/python-venv/tox/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/tronde/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/tronde/python-venv/tox/bin/ansible
  python version = 3.10.3 (main, Mar 18 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.1.1
  libyaml = True

$ tox --version
3.24.5 imported from /home/tronde/python-venv/tox/lib64/python3.10/site-packages/tox/__init__.py
registered plugins:
    tox-lsr-2.10.1 at /home/tronde/python-venv/tox/lib64/python3.10/site-packages/tox_lsr/hooks.py

$ stat ~/.config/linux-system-roles.json 
  File: /home/jkastning/.config/linux-system-roles.json
  Size: 3129      	Blocks: 8          IO Block: 4096   regular file
Device: 28h/40d	Inode: 1116716     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/tronde)   Gid: ( 1000/tronde)
Context: unconfined_u:object_r:user_home_t:s0
Access: 2022-03-31 13:48:38.045493817 +0200
Modify: 2022-02-28 05:52:07.624511590 +0100
Change: 2022-03-31 13:47:56.840625865 +0200
 Birth: 2022-02-28 05:52:07.624511590 +0100

Installed Packages
standard-test-roles-inventory-qemu.noarch     4.10-3.fc35       @fedora
~~~

The following try fails. Unfortuantely I don't understand why and don't know how to fix it.

~~~
(tox) [tronde@t14s pam_pwd]$ tox -e qemu-ansible-core-2.11 -- --debug --config ~/.config/linux-system-roles.json --image-name centos-8 -u root -- tests/tests_default.yml
qemu-ansible-core-2.11 installed: ansible-core==2.11.10,beautifulsoup4==4.10.0,cffi==1.15.0,cryptography==36.0.2,Jinja2==3.1.1,MarkupSafe==2.1.1,packaging==21.3,productmd==1.33,pycparser==2.21,pyparsing==3.0.7,PyYAML==6.0,resolvelib==0.5.4,ruamel.yaml==0.17.21,ruamel.yaml.clib==0.2.6,six==1.16.0,soupsieve==2.3.1
qemu-ansible-core-2.11 run-test-pre: PYTHONHASHSEED='1362769028'
qemu-ansible-core-2.11 run-test: commands[0] | python /home/tronde/python-venv/tox/lib64/python3.10/site-packages/tox_lsr/test_scripts/runqemu.py --debug --config /home/tronde/.config/linux-system-roles.json --image-name centos-8 -u root -- tests/tests_default.yml
Traceback (most recent call last):
  File "/home/tronde/python-venv/tox/lib64/python3.10/site-packages/tox_lsr/test_scripts/runqemu.py", line 590, in <module>
    main()
  File "/home/tronde/python-venv/tox/lib64/python3.10/site-packages/tox_lsr/test_scripts/runqemu.py", line 579, in main
    image = get_image_config(args)
  File "/home/tronde/python-venv/tox/lib64/python3.10/site-packages/tox_lsr/test_scripts/runqemu.py", line 302, in get_image_config
    config = json.load(configfile)
  File "/usr/lib64/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 91 column 3 (char 3125)
ERROR: InvocationError for command /home/tronde/ansible/roles/pam_pwd/.tox/qemu-ansible-core-2.11/bin/python /home/tronde/python-venv/tox/lib64/python3.10/site-packages/tox_lsr/test_scripts/runqemu.py --debug --config /home/tronde/.config/linux-system-roles.json --image-name centos-8 -u root -- tests/tests_default.yml (exited with code 1)
_______________________________________________________________________________________________ summary _______________________________________________________________________________________________
ERROR:   qemu-ansible-core-2.11: commands failed
~~~

Is there something wrong with my `~/.config/linux-system-roles.json`? Here is its content:

~~~
$ cat ~/.config/linux-system-roles.json
{
  "repositories": [
    "linux-system-roles/certificate",
    "linux-system-roles/cockpit",
    "linux-system-roles/crypto_policies",
    "linux-system-roles/firewall",
    "linux-system-roles/ha_cluster",
    "linux-system-roles/kdump",
    "linux-system-roles/kernel_settings",
    "linux-system-roles/logging",
    "linux-system-roles/metrics",
    "linux-system-roles/mssql",
    "linux-system-roles/nbde_client",
    "linux-system-roles/nbde_server",
    "linux-system-roles/network",
    "linux-system-roles/postfix",
    "linux-system-roles/selinux",
    "linux-system-roles/ssh",
    "linux-system-roles/storage",
    "linux-system-roles/timesync",
    "linux-system-roles/tlog",
    "linux-system-roles/tuned",
    "linux-system-roles/vpn"
  ],
  "images": [
    {
      "name": "fedora-34",
      "compose": "https://kojipkgs.fedoraproject.org/compose/cloud/latest-Fedora-Cloud-34/compose/",
      "openstack_image": "Fedora-Cloud-Base-34",
      "upload_results": true,
      "min_ansible_version": "2.9"
    },
    {
      "name": "fedora-35",
      "compose": "https://kojipkgs.fedoraproject.org/compose/cloud/latest-Fedora-Cloud-35/compose/",
      "openstack_image": "Fedora-Cloud-Base-35",
      "upload_results": true,
      "min_ansible_version": "2.9"
    },
    {
      "name": "centos-6",
      "source": "https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud-1907.qcow2c",
      "openstack_image": "CentOS-6-x86_64-GenericCloud-released-latest",
      "upload_results": true,
      "env": {
        "TEST_EXTRA_SSH_ARGS": "-o PubkeyAcceptedKeyTypes=+ssh-rsa"
      },
      "setup": [
        {
          "name": "Change repos to use vault",
          "hosts": "all",
          "become": true,
          "gather_facts": false,
          "tasks": [
            { "name": "fix yum repos to use vault.centos.org",
              "shell": "set -euo pipefail; for file in /etc/yum.repos.d/CentOS-*.repo; do if ! grep '^baseurl=.*vault[.]centos[.]org' \"$file\"; then sed -i -e 's,^mirrorlist,#mirrorlist,' -e 's,^#baseurl=,baseurl=,' -e 's,mirror.centos.org/centos/$releasever,vault.centos.org/6.10,' \"$file\"; fi; done",
              "no_log": true
            }
          ]
        }
      ]
    },
    {
      "name": "centos-7",
      "source": "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2c",
      "openstack_image": "CentOS-7-x86_64-GenericCloud-released-latest",
      "env": {
        "TEST_SSHD_USEDNS_NO": "True"
      },
      "upload_results": true
    },
    {
      "name": "centos-8",
      "source": "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2",
      "openstack_image": "CentOS-8-x86_64-GenericCloud-released-latest",
      "upload_results": true,
      "setup": [
        {
          "name": "Enable HA repos",
          "hosts": "all",
          "become": true,
          "gather_facts": false,
          "tasks": [
            { "name": "Enable HA repos",
              "command": "dnf config-manager --set-enabled ha"
            }
          ]
        }
      ]
    },
  ]
}
~~~

Help is much appreciated. Please notice that I'm pretty new to `tox-lsr`. Please bear with me. Maybe I'm just holding/using it wrong.

**Comment by richm** [comment]
At line 91 of linux-system-roles.json there is `},` - remove the comma `,` - also, this is not the latest file - try downloading the latest file from https://raw.githubusercontent.com/linux-system-roles/linux-system-roles.github.io/master/download/linux-system-roles.json
